require: rubocop-rails

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "frontend/*"
    - "db/migrate/*.rb"
    - "db/fixtures/development/*.rb"
    - "db/fixtures/production/*.rb"
  DisplayCopNames: true

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*_spec.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails/Present:
  Exclude:
    - 'bin/bundle'

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 160

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/PerceivedComplexity:
  Max: 9
