version: '3'
services:
  db:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    networks:
      - app
  backend:
    container_name: backend
    build: ./backend
    command: /bin/sh -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    environment:
      RAILS_DATABASE_HOST: db
      RAILS_DATABASE_USER: pguser
      RAILS_DATABASE_PASSWORD: password
    depends_on:
      - db
    networks:
      - app
  frontend:
    container_name: frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: "yarn start"
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app
volumes:
  db:
networks:
  app:
